vich_uploader:
    db_driver: orm
###############################################################################
    mappings:
        etudiant_image:
            uri_prefix: /images/etudiants
            upload_destination: '%kernel.project_dir%/public/images/etudiants'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
####################################################################################
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
